
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utkxuvldiveojhnzfsca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0a3h1dmxkaXZlb2pobnpmc2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNjQzMjQsImV4cCI6MjA2Mjk0MDMyNH0.J3UJRs2LFEXccnk617KZwSQQb4aMDA-Z-uj4vjD1IBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true, // 启用URL中的会话检测
    }
  }
);
